### ISSUE TITLE
ACCEPTANCE_TESTING: Add Command Invalid Address Message Inaccurate

### ISSUE THREAD

**Issue by soonwj** [CS2103AUG2017-T16-B1/main#154]
![image](https://user-images.githubusercontent.com/29708420/32363199-0c86bb90-c0a9-11e7-9202-f6f39fbfd7a3.png)

The message says that the address can take in any value and must end with S appended with 6 digits separated from the rest by one or multiple space(s). As shown in the diagram above, the address I input is 'A S956465' which satisfies the requirement stated, but it still throw an error.

**Comment by Kennard123661** [comment]
Hey! Thanks for the heads up. I just fixed it, gonna PR my change now 👍 

![image](https://user-images.githubusercontent.com/17818981/32491434-9ef5744e-c3f1-11e7-931c-61156244d4fa.png)
