### ISSUE TITLE
ACCEPTANCE_TESTING: Cannot reopen app after closing

### ISSUE THREAD

**Issue by soonwj** [CS2103AUG2017-T16-B1/main#156]
![image](https://user-images.githubusercontent.com/29708420/32363758-d2f88824-c0ab-11e7-8dda-511284454003.png)
Addressbook.xml screenshot for reference.

**Comment by Kennard123661** [comment]
@soonwj  are you able to provide us with the storage file? Or could you tell us the steps you did to produce this error? Thanks!

**Comment by soonwj** [comment]
I entered the command as in: https://github.com/CS2103AUG2017-T16-B1/main/issues/154 and as mentioned, the invalid error popped up. But as u can see in the above picture, the "invalid address" was still saved to the first contact shown. So when i closed and reopened the app, an exception was thrown while trying to generate the PersonList.
