### ISSUE TITLE
ACCEPTANCE_TESTING: add examples can't be added

### ISSUE THREAD

**Issue by itsdickson** [CS2103AUG2017-T16-B1/main#157]
example of Betsy Crowe cannot be added (UserGuide) 

![image](https://user-images.githubusercontent.com/30717938/32363882-79f7430e-c0ac-11e7-89e9-a126f6076b52.png)

furthermore, the example provided in the error message from invalid add command is also invalid

![image](https://user-images.githubusercontent.com/30717938/32363856-5bfb71fe-c0ac-11e7-9345-f99de0fbdea3.png)

**Comment by ktnc985** [comment]
Fixed, thanks for pointing it out!
