### ISSUE TITLE
ACCEPTANCE TESTING: [UNSURE] Parcels having the same tracking ID

### ISSUE THREAD

**Issue by itsdickson** [CS2103AUG2017-T16-B1/main#160]
I'm unsure if this is a bug, but are parcels supposed to have the same tracking ID? If not, should have a check for duplicate tracking ID.

![image](https://user-images.githubusercontent.com/30717938/32364017-6c76244c-c0ad-11e7-8a08-52809ac94aa1.png)

**Comment by ktnc985** [comment]
This is intended
